# Generated by Django 2.1.4 on 2019-03-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=255)),
                ('minnumberplayers', models.PositiveSmallIntegerField()),
                ('maxnumberplayers', models.PositiveSmallIntegerField()),
                ('gameplaylength', models.PositiveSmallIntegerField()),
                ('iscooperative', models.BooleanField()),
            ],
            options={
                'db_table': 'boardgame',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('games', models.ManyToManyField(to='showdown.BoardGame')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.PositiveSmallIntegerField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField()),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='showdown.Participant'),
        ),
    ]
